api/api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views
from . import views


from django.urls import path

router = routers.DefaultRouter()
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    #path('', include(router.urls)),
    path('', views.apiOverview, name='apiOverview'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('user-list/',views.showAllUser,name='user list'),
    path('user-detail/<int:pk>',views.showUser,name='user detail'),
    path('user-create/',views.createUser,name='user create'),
    path('user-update/<int:pk>',views.updateUser,name='user update'),
    path('user-delete/<int:pk>',views.deleteUser,name='user delete'),
    #path('login/',views.LoginView.as_view(),name='user login'),
    path('login/',views.loginUser,name='user login'),
    path('course-create/',views.createCourse,name='course create'),
    path('course-list/',views.showAllCourse,name='course list'),
    path('lecture-create/',views.createLecture,name='lecture create'),
    path('lecture-list/',views.showAllLecture,name='lecture list'),

    
    
]

api/classroom/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users_classroom.urls')),
    path('courseMaterials/', include('courseMaterials.urls')),
    path('api/', include('api.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/users_classroom/urls.py
from django.urls import path
from . import views

urlpatterns= [
    path('', views.index, name='index'),
    path('register/', views.register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('record/', views.user_rec, name='user_rec'),
    path('notes/', views.notes, name='notes'),
    path('note', views.note, name='note'),
    path('notes/note', views.note, name='note'),

]

api/users_classroom/models.py
from django.db import models
from django.contrib.auth.models import User
import os

from django.utils.functional import empty

# Create your models here.

def PicPath(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.pk:
        filename = 'ProfilePics/{}.{}'.format(instance.pk, ext)
    return os.path.join(upload_to, filename)

class UserProfile(models.Model):
    
    #creating a relationship with user class (not inheriting)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #adding additional attributes
    UploadPicture = models.ImageField(upload_to=PicPath, verbose_name="Profile Picture", blank=True)
    teacher = 'teacher'
    student = 'student'
    empty= None
    user_types = [
        (empty,None),
        (teacher, 'teacher'),
        (student, 'student'),
    ]
    user_type = models.CharField(max_length=10, choices=user_types, default=empty)

    def __str__(self):
        return self.user.username

class Note(models.Model):
    title = models.CharField(max_length=200, null=True)
    details = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.title

api/users_classroom/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.functional import empty
from users_classroom.models import UserProfile

class UserForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta():
        model = User
        fields = ('username','first_name','last_name', 'email', 'password1', 'password2')
        labels = {
        'password1':'Password',
        'password2':'Confirm Password',
        }
class UserProfileForm(forms.ModelForm):
    teacher = 'teacher'
    student = 'student'
    empty=None
    user_types = [
        (empty, None),
        (student, 'student'),
        (teacher, 'teacher'),
    ]
    user_type = forms.ChoiceField(required=True, choices=user_types)

    class Meta():
        model = UserProfile
        fields = ('UploadPicture', 'user_type')

api/users_classroom/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from users_classroom.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Note

# Create your views here.
def index(request):
    return render (request, 'home.html')

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account is not avaiable")
        else:
            return HttpResponse("Enter your correct password or username or both")

    else:
        return render(request, 'users_classroom/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def user_rec(request):  
    return render(request, 'users_classroom/audiorec.html')  

def register(request):
    
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'users_classroom/registration.html', {'registered':registered,
                            'user_form':user_form, 'profile_form':profile_form})


@login_required
def note(request):
    if request.method == 'POST':
        title = request.POST['note-title']
        details = request.POST['note-text']

        note = Note.objects.create(title=title, details=details)
        note.save()
        return render (request, 'home.html')
    else:
        return render (request, 'home.html')

@login_required
def notes(request):  

    context = {
        'notes': Note.objects.all()
    }
    return render(request, 'users_classroom/notes.html', context) 

api/users_classroom/templates/users_classroom/audiorec.html
{% extends 'home.html' %}

{% block content %}
<!doctype html>
<html>
    <head > 
        <title>Audio Recorder</title>
        <style type="text/css">
            body {
                background-color: lightblue;
                position: absolute;
                display: -webkit-box;
                display: -webkit-flex;
                display: -ms-flexbox;
                display: flex;
                -webkit-box-pack: center;
                -webkit-justify-content: center;
                    -ms-flex-pack: center;
                        justify-content: center;
                -webkit-box-align: center;
                -webkit-align-items: center;
                    -ms-flex-align: center;
                        align-items: center;
                height: 100%;
                width: 100%;
                margin: 0;
            }
            .holder {
                background-color: #4c474c;
                background-image: -webkit-gradient(linear, left bottom, left top, from(#4c474c), to(#141414));
                background-image: -o-linear-gradient(bottom, #4c474c 0%, #141414 100%);
                background-image: linear-gradient(0deg, #4c474c 0%, #141414 100%);
                border-radius: 50px;
            }
            [data-role="controls"] > button {
                margin: 50px auto;
                outline: none;
                display: block;
                border: none;
                background-color: #D9AFD9;
                background-image: -webkit-gradient(linear, left bottom, left top, from(#D9AFD9), to(#97D9E1));
                background-image: -o-linear-gradient(bottom, #D9AFD9 0%, #97D9E1 100%);
                background-image: linear-gradient(0deg, #D9AFD9 0%, #97D9E1 100%);
                width: 100px;
                height: 100px;
                border-radius: 50%;
                text-indent: -1000em;
                cursor: pointer;
                -webkit-box-shadow: 0px 5px 5px 2px rgba(0,0,0,0.3) inset, 
                    0px 0px 0px 30px #fff, 0px 0px 0px 35px #333;
                        box-shadow: 0px 5px 5px 2px rgba(0,0,0,0.3) inset, 
                    0px 0px 0px 30px #fff, 0px 0px 0px 35px #333;
            }
            [data-role="controls"] > button:hover {
                background-color: #ee7bee;
                background-image: -webkit-gradient(linear, left bottom, left top, from(#ee7bee), to(#6fe1f5));
                background-image: -o-linear-gradient(bottom, #ee7bee 0%, #6fe1f5 100%);
                background-image: linear-gradient(0deg, #ee7bee 0%, #6fe1f5 100%);
            }
            [data-role="controls"] > button[data-recording="true"] {
                background-color: #ff2038;
                background-image: -webkit-gradient(linear, left bottom, left top, from(#ff2038), to(#b30003));
                background-image: -o-linear-gradient(bottom, #ff2038 0%, #b30003 100%);
                background-image: linear-gradient(0deg, #ff2038 0%, #b30003 100%);
            }
            [data-role="recordings"] > .row {
                width: auto;
                height: auto;
                padding: 20px;
            }
            [data-role="recordings"] > .row > audio {
                outline: none;
            }
            [data-role="recordings"] > .row > a {
                display: inline-block;
                text-align: center;
                font-size: 20px;
                line-height: 50px;
                vertical-align: middle;
                width: 50px;
                height: 50px;
                border-radius: 20px;
                color: #fff;
                font-weight: bold;
                text-decoration: underline;
                background-color: #0093E9;
                background-image: -webkit-gradient(linear, left bottom, left top, from(#0093E9), to(#80D0C7));
                background-image: -o-linear-gradient(bottom, #0093E9 0%, #80D0C7 100%);
                background-image: linear-gradient(0deg, #0093E9 0%, #80D0C7 100%);
                float: right;
                margin-left: 20px;
                cursor: pointer;
            }
            [data-role="recordings"] > .row > a:hover {
                text-decoration: none;
            }
            [data-role="recordings"] > .row > a:active {
                background-image: -webkit-gradient(linear, left top, left bottom, from(#0093E9), to(#80D0C7));
                background-image: -o-linear-gradient(top, #0093E9 0%, #80D0C7 100%);
                background-image: linear-gradient(180deg, #0093E9 0%, #80D0C7 100%);
            }
        </style>
        <script type="text/javascript" src="https://code.jquery.com/jquery.min.js"></script>
        <script src="https://stephino.github.io/dist/recorder.js"></script>
        <script>
            jQuery(document).ready(function () {
                var $ = jQuery;
                var myRecorder = {
                    objects: {
                        context: null,
                        stream: null,
                        recorder: null
                    },
                    init: function () {
                        if (null === myRecorder.objects.context) {
                            myRecorder.objects.context = new (
                                    window.AudioContext || window.webkitAudioContext
                                    );
                        }
                    },
                    start: function () {
                        var options = {audio: true, video: false};
                        navigator.mediaDevices.getUserMedia(options).then(function (stream) {
                            myRecorder.objects.stream = stream;
                            myRecorder.objects.recorder = new Recorder(
                                    myRecorder.objects.context.createMediaStreamSource(stream),
                                    {numChannels: 1}
                            );
                            myRecorder.objects.recorder.record();
                        }).catch(function (err) {});
                    },
                    stop: function (listObject) {
                        if (null !== myRecorder.objects.stream) {
                            myRecorder.objects.stream.getAudioTracks()[0].stop();
                        }
                        if (null !== myRecorder.objects.recorder) {
                            myRecorder.objects.recorder.stop();

                            // Validate object
                            if (null !== listObject
                                    && 'object' === typeof listObject
                                    && listObject.length > 0) {
                                // Export the WAV file
                                myRecorder.objects.recorder.exportWAV(function (blob) {
                                    var url = (window.URL || window.webkitURL)
                                            .createObjectURL(blob);

                                    // Prepare the playback
                                    var audioObject = $('<audio controls></audio>')
                                            .attr('src', url);

                                    // Prepare the download link
                                    var downloadObject = $('<a>&#9660;</a>')
                                            .attr('href', url)
                                            .attr('download', new Date().toUTCString() + '.wav');

                                    // Wrap everything in a row
                                    var holderObject = $('<div class="row"></div>')
                                            .append(audioObject)
                                            .append(downloadObject);
                                            // Append to the list
                                    listObject.append(holderObject);
                                });
                            }
                        }
                    }
                };

                // Prepare the recordings list
                var listObject = $('[data-role="recordings"]');

                // Prepare the record button
                $('[data-role="controls"] > button').click(function () {
                    // Initialize the recorder
                    myRecorder.init();

                    // Get the button state 
                    var buttonState = !!$(this).attr('data-recording');

                    // Toggle
                    if (!buttonState) {
                        $(this).attr('data-recording', 'true');
                        myRecorder.start();
                    } else {
                        $(this).attr('data-recording', '');
                        myRecorder.stop(listObject);
                    }
                });
            });
        </script>
    </head>
    <body>
        <div class="holder">
            <div data-role="controls">
                <button>Record</button>
            </div>
            <div data-role="recordings"></div>
        </div>
        {% endblock %}
    </body>
</html>
            
        

api/users_classroom/templates/users_classroom/login.html
{% extends 'home.html' %}

{% block content %}
{% load static %}

<body  style="background-color: #a9e9e4 ;">

<div class="container" >
  <div class="container-fluid">
    <div class="text-center mt-5">
      <form method="post" style="max-width: 380px;margin: auto;padding-top: 30px;">
        {% csrf_token %}

        <h1 class="h3 mb-3 font-weight-normal">Please Log In</h1>
        <label for="username"></label>
        <input type="text" class="form-control" placeholder="Username" name="username" maxlength="150" autofocus required id="id_username">

        <label for="password"></label>
        <input type="password" class="form-control" placeholder="Password" name="password" type="password" >

        <input class="btn btn-primary mt-3"  type="submit" value="Login">
        
        <input class="btn btn-primary mt-3" type="reset" value="Reset" class="btn btn-reset btn-primary" style="padding-top: 3px;" />
        <input class="btn btn-primary mt-3" type="button" value="Cancel" class="btn btn-cancel btn-primary" style="padding-top: 3px;"
          onclick="location.href='{% url 'index' %}'">
      </form>
    </div>
  </div>
</div>
{% endblock %}
</body>

api/users_classroom/templates/users_classroom/notes.html
{% extends 'home.html' %}{% load static %}

{% block content %}
<!-- internal css Start -->
<Style>
    .notes{
        padding: 1rem;
        background-color: #fff;
        border-radius: 5px;
        margin: 1rem 0;
        background-color: lightseagreen
    }
    .note-counter, .note-text{
        font-size: 1.4rem;
    }
    .note-title{
        font: 1.6rem;
    }
    .note-btn{
        padding: 7px;
        margin-top: 5px;
        background-color: red;
        outline: none;
        border: none;
        border-radius: 3px;
        color: #fff;
    }
    .edit-btn{
        background-color: rosybrown;
    }
</Style>
<!-- internal css End -->

<!-- html Code Start -->
<section>
    <div class="container">
        <h2>Notes</h2>
        <hr>
        <div class="notes" id="notes">
            <!-- Add Note Button -->
{% if user.is_authenticated %}
<div class="col-md-4 mt-4">
<button style="margin-left: -5%" id="add-note">Add Note</button><br><br>
</div>
{% endif %}
            {% for note in notes %}
            <div class="note">
                <p class="note-counter">Note{{ note.id }}</p>
                <h3 class="note-title">{{ note.title }}</h3>
                <p class="note-text">{{ note.details }}</p>
                <button class="note-btn edit-btn">Edit Note</button>
                <button class="note-btn">Delete Note</button>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- html Code End -->


<!-- Note form Start -->
<div class="bg-modal">
    <div class="modal-content">
        <div class="close">+</div>
        <h1>My Notes</h1>
        <form action="note" method="POST">
            {% csrf_token %}
            <input type="text" name="note-title" placeholder="Note title">
            <input class="ta" type="text" name="note-text" placeholder="Note details">
            <!-- <textarea name="note-text" placeholder="Note details"></textarea> -->

            <button id="add-btn" type="submit">Add Note</button>
        </form>
    </div>
</div>
<!-- Note form End -->

<!-- Note Modal JS Start -->
<script>
    document.getElementById('add-note').addEventListener('click', function() {
        document.querySelector('.bg-modal').style.display = 'flex';
    })

    document.querySelector('.close').addEventListener('click', function() {
        document.querySelector('.bg-modal').style.display = 'none';
    })
</script>
<!-- Note Modal JS End -->

{% endblock %}

api/users_classroom/templates/users_classroom/registration.html
{% extends 'home.html' %}
{% load static %}
{% block content %}

{% if registered %}
<br>
<br>
<h3 style="font-size: medium;">Congratulations you have signed up sucessfully!!!</h3>

{% else %}
<footer class="page-footer" style="background-color: rgb(208, 235, 250);" >

  <body style="background-color: #a9e9e4 ;">
    <div class="container">
      <div class="row">
        <div class="col">
          
        </div>
        <div class="col-6">
          <form method="post" enctype="multipart/form-data" style="text-align: center;">
            {% csrf_token %}
             <div class="container signup" style="height: auto">
               <h4 style="padding-top: 15px;">Fillup the form: </h4>
               <div class="row">
                   <div class="col-xxl-6  col-centered" style="text-align: center">
                       <label for="username" class="form-label"></label>
     
                       <div class="input-group" >
     
     
                     <input type="text" class="form-control" placeholder="Username" name="username" maxlength="150" autofocus required id="id_username">
     
                       </div>
                       <div class="invalid-feedback">
                       Valid username is required
                   </div> 
     
                   </div>
                 </div>  
     
                   <div class="row">
                       <div class="col-xxl-6  col-centered">
                           <label for="firstName" class="form-label"></label>
     
                           <input type="text" placeholder="First Name" class="form-control" required name="first_name" maxlength="150" id="id_first_name">
     
                           <div class="invalid-feedback">
                           Valid first name is required
                           </div>
                       </div>
                 </div>  
                 <div class="row">    
                       <div class="col-xxl-6  col-centered" >
                           <label for="lastName" class="form-label"></label>
     
                           <input type="text" name="last_name" placeholder="Last Name" class="form-control" required maxlength="150" id="id_last_name">
     
                           <div class="invalid-feedback">
                           Valid last name is required
                           </div>
                       </div>
                 </div>
     
                 <div class="row">      
     
                   <div class="col-xxl-6  col-centered" >
     
                       <label for="email" class="form-label"></label>
     
     
                       <input type="email" placeholder="Email" name="email" class="form-control" required id="id_email">
     
     
                   </div>
                 </div>
     
                     <div class="row">
                           <div class="col-xxl-6  col-centered" >
                           <label for="password1"></label>
     
     
                           <input type="password" class="form-control" placeholder="Password" name="password1" autocomplete="new-password"  required id="id_password1"> 
     
                           </div>
                     </div>  
                      <div class="row">
                           <div class="col-xxl-6  col-centered" >
                           <label for="password2"></label>
     
                          <input type="password" name="password2" autocomplete="new-password" class="form-control" placeholder="Confirm password" required id="id_password2">
     
                           </div>
                     </div>
     
                       <div class="row">
                           <div class="col-xxl-6  col-centered mt-4" >
                               <div class="input-group">
     
                                    <input type="file" name="UploadPicture" class="form-control" placeholder="Profile Picture" accept="image/*" id="id_UploadPicture">
     
     
     
                               </div>
                           </div>  
     
                           <div class="row " >
                                 <div class="col-xxl-6  col-centered mt-4" >
                               <div class="form-group select_user" >
                                 <select name="user_type" required id="id_user_type" >
                                   <option value="">None</option>
     
                                   <option value="student" selected>Student</option>
     
                                   <option value="teacher">Teacher</option>
     
                                 </select>
     
                              </div>
     
                            </div>
                           </div>
                       <div class="" style="padding-top:30px; ">
     
                           <input type="submit"  value="Register" class="btn btn-cancel btn-primary" >
     
                       <input type="reset" value="Reset" class="btn btn-cancel btn-primary" >
                       <input type="button" value="Cancel" class="btn btn-cancel btn-primary" onclick="location.href='{% url 'index' %}'" >
     
     
                       </div>
                   </div>  
                   </div>    
     
               </form>
        </div>
        <div class="col">
          
        </div>
      </div>
    </div>











    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>

{%endif%}
{% endblock %}








  




  